#164069171 create empty react project
andela/ah-aquaman-frontend pull request #1
Opened 2019-04-01 13:26 UTC by wasibani-roy

**What does this PR do**
This PR creates an empty react project

**Description of tasks to be completed**
- Ensure that we create an empty react application

**How can this be tested??**
Create a folder e.g `ah-frontend`
- Navigate to the project directory

   `cd ah-frontend`

- Clone the project

   `git clone https://github.com/andela/ah-aquaman-frontend.git`

-  Install dependencies using `npm install`
- Run Application locally using `npm start

**Any background context you want to provide**
N/A

**What are the relevant pivotal tracker stories**

- [#164069171](https://www.pivotaltracker.com/story/show/164069171)

2019-04-01 13:45 UTC, CryceTruly requested changes
Thanks, @Roy Wasibani for the great work, However first add nodemodules to .gitignore as `npm install ` will create the folder for everyone else.

2019-04-01 14:30 UTC, CryceTruly approved these changes

2019-04-01 14:32 UTC, Peace-Apple approved these changes
Good work @wasibani-roy

2019-04-01 15:05 UTC, AmosWels requested changes
Goodwork @wasibani-roy, please consider amending your commit message `footer` to follow the team conventions as agreed here https://github.com/andela/engineering-playbook/tree/test-branch/5.%20Developing/Conventions#message-footer.

- For `chores`: use `Finishes`, for `Bugs`: use `Fixes` and for `features`: use `Delivers`

- Also consider creating an `assets` directory in the `src` folder where all the css will be housed. Then move `App.css` file there and update the path in the `App.js`

2019-04-01 15:05 UTC, AmosWels commented on .babelrc
> +}
Add a new line to this file

2019-04-01 15:05 UTC, AmosWels commented on src/App.css
> +}
Same here, add a new line

2019-04-01 15:05 UTC, AmosWels commented on src/App.js
> +export default App;
Same here, add a new line

2019-04-01 15:05 UTC, AmosWels commented on src/index.html
> +</html>
Add a new line here

2019-04-01 15:05 UTC, AmosWels commented on src/index.js
> +ReactDOM.render(<App />, document.getElementById("root"));
Add a new line here

2019-04-01 15:05 UTC, AmosWels commented on webpack.config.js
> +};
Add a new line here

2019-04-01 16:01 UTC, Peace-Apple approved these changes
Thanks for implementing the feedback

2019-04-01 16:07 UTC, joelethan approved these changes

2019-04-01 16:07 UTC, joelethan commented on .babelrc
> +}
@wasibani-roy Most of the files do not have an extra line at the end of the code, could you please add them

2019-04-01 16:13 UTC, CryceTruly approved these changes

2019-04-02 05:57 UTC, AmosWels requested changes
Goodwork @wasibani-roy, please check how you named your `assets` folder. You named it from `assests`. Also check that your PR message is well formatted. See the screenshot below.

![image](https://user-images.githubusercontent.com/37612799/55379260-26865700-5525-11e9-8a38-9304ea6b4134.png)

2019-04-02 06:23 UTC, CryceTruly approved these changes

2019-04-02 06:28 UTC, CryceTruly requested changes
Thanks for the Good work @wasibani-roy, However, the story also consists of configuring a linting library like eslint using the Airbnb option, Let's consider adding it.

2019-04-02 06:56 UTC, joelethan commented
@CryceTruly We do not need the implementation of Airbnb. It was only to be implemented if we used create-react-app, however, we set the whole app from scratch, so this implementation is not needed.

2019-04-02 07:49 UTC, BagzieGracious approved these changes
Thank you @wasibani-roy for the add work

2019-04-02 07:50 UTC, joelethan approved these changes

2019-04-02 08:09 UTC, CryceTruly approved these changes

2019-04-02 08:16 UTC, Peace-Apple approved these changes
Good work @wasibani-roy, thanks for adding eslint

2019-04-02 08:52 UTC, AmosWels approved these changes

2019-04-02 08:52 UTC, merged