164069173 Setup testing environment
andela/ah-aquaman-frontend pull request #6
Opened 2019-04-02 14:45 UTC by joelethan

#### What does this PR do?
- This PR sets up the testing environment for the react project
#### Description of Task to be completed?
- Install packages and dependencies for testing
- Write a test that the application renders without crushing
#### How should this be manually tested?
- Clone the [repo](https://github.com/andela/ah-aquaman-frontend) and cd into `ah-aquaman-frontend`
- checkout the branch `ch-setup-test-env-164069173`
- Run the commands below to install packages and run tests
    -  npm install
    -  npm test
#### What are the relevant pivotal tracker stories?
- [#164069173](https://www.pivotaltracker.com/story/show/164069173)

#### Screenshots (if appropriate)
- expected output
<img width="865" alt="Screenshot 2019-04-02 at 17 40 42" src="https://user-images.githubusercontent.com/6951438/55411608-9ec53a80-556e-11e9-9b16-819becf49184.png">

2019-04-02 14:55 UTC, BagzieGracious approved these changes
Thank you @joelethan, for your good work

2019-04-02 15:07 UTC, Peace-Apple approved these changes
Good work @joelethan

2019-04-02 15:37 UTC, wasibani-roy approved these changes

2019-04-02 16:34 UTC, AmosWels commented on package.json
> +    "test": "react-scripts test --watchAll",
Can remove the `--watchAll` so testers can select to use it when they need to

2019-04-02 16:37 UTC, AmosWels requested changes
Goodwork @joelethan , please create a `__tests__` folder in the src director and add the `App.test.js` to that folder.

2019-04-03 07:02 UTC, Peace-Apple commented
Good work @joelethan, please rebase with the develop branch to resolve the conflicts your branch is having.

2019-04-03 09:14 UTC, AmosWels approved these changes

2019-04-03 09:14 UTC, merged